# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!
inhibit_all_warnings!

#ALEX

pod 'FrameAccessor'
pod 'Timepiece'
pod 'ChameleonFramework'
pod 'MBProgressHUD'
pod 'MGSwipeTableCell'
pod 'InfinitePagingView'
pod 'pop'
pod 'FrameAccessor'
pod 'OAuthSwift'

#VADIM

pod 'Alamofire'
pod 'Parsimmon', '~> 0.3.4'
pod 'SwiftyJSON'
pod 'UberKit'
# Simulate 3D Touch :-/
pod 'FLEX', '~> 2.0', :configurations => ['Debug']
